### ISSUE TITLE
It doesn't work for after logic lite 8

### ISSUE THREAD

**Issue by trampeagle** [afterlogic/aurora-module-mail-change-password-hmailserver-plugin#1]
after adding the module. the tab is not shown in admin tab. it is nothing.

**Comment by afterlogic-support** [comment]
Make sure you follow the instructions for building static files after adding the module as shown at:
https://afterlogic.com/docs/webmail-lite-8/installation/adding-modules
Also, it may be needed to purge data/cache/ directory content.

**Comment by china-fengguan** [comment]
It can only come under https as it is tested here. As the instruction, login and password have been provided in same tab, also I open ChangePasswordWebclient.config.json module so that the change password button will come when I log on with my email id, which is for my own guess, please guide on this. log on with email account, and click change password, input old password and new password twice, it pops up sucessful message for changing my password. unfortunately, it is not the time for cheer, the password was not changed finally.
please kindly guide me more after the instruction in readme.md.
there is very few log, so hard to find the issue because everything looks fine. check the following log:

[76efbc8a] API: Mail::ChangePassword
[76efbc8a] Execute subscription: MailChangePasswordHmailserverPlugin::onBeforeChangePassword

**Comment by afterlogic-support** [comment]
Well yes, enabling ChangePasswordWebclient.config.json module is required to get the change password button.
Not sure why the password change itself won't for you, off-head I can suggest to make sure [COM support](http://php.net/COM) is enabled in your PHP configuration:

**Comment by china-fengguan** [comment]
related COM extension, as well as local activiate right for iis_usrs (using IIS) has been configured. 
One test here, after changing password "successfully", I tried to send email, and report an error, password is not correct. it looks the password has been changed partially, but not fully changed in hmailserver database ( using mysql),  grateful for any guide on what I should check for this.

**Comment by china-fengguan** [comment]
I have installed pmailserver PHPWebAdmin, it works well for changing password, FYI.
But don't really want to let user change their password with this page, beacausr there is only one administrator account for that.

**Comment by china-fengguan** [comment]
Here is a question for db configuration, has it to be same with hmailserver db or not? changePassword method invoke hmailserver service or directly operate hmailserver table? If hmailserver table names have prefix hm_, doesn't it affact changePassword function?
I have tried point to the same database and the issue is still there, nothing changed at DB side.

**Comment by afterlogic-support** [comment]
WebMail database tables are completely separate, and the plugin doesn't deal with hMailServer tables, password change is done via API offered by hMailServer - that would be why COM extension is needed.

We'll have this rechecked on the latest WebMail Lite release and will get back to you.

**Comment by afterlogic-support** [comment]
Looks like there was a bug in the code. To correct it, replace line 119 in **Module.php** file:
`if (($oAccount instanceof \CMailAccount) && $this->oBaseApp && $this->oAdminAccount)`
with:
`if (($oAccount instanceof \Aurora\Modules\Mail\Classes\Account) && $this->oBaseApp && $this->oAdminAccount)`

Hope it helps.

**Comment by china-fengguan** [comment]
great job!!
